### PR TITLE
Renaming repo and every instance of "ffai" to "botbowl"

### LINKED ISSUE #170: Rename repo to bot-bowl
This is a better name and connects better with our competition.

I suggest we first make a PR that changes instances of FFAI in all the files to Bot Bowl, bot-bowl, bot_bowl, depending on the context, and when merged to main we rename the repo.

### PR DESCRIPTION
**Pull request by njustesen**
Fixes #170
- #170

### CODE REVIEW

**Comment by mrbermell** [comment]
Massive PR! :laughing: 

 I've tried installing in a few different ways and it never breaks. A few things: 
 1. The first picture in the README.md is 404. 
 2. Why keep "Fantasy Football AI" when getting rid of "ffai"? 
 2. I suggest clarifying the distinction between the module `botbowl` and the competition Bot Bowl with the capital letters and the space between "bot" and "bowl", I suggest to simply add this in the README.md where Bot Bowl is first mentioned.

**Comment by njustesen** [comment]
Feel free to add fixes to three things you pointed out. We also need to check if the tutorials makes sense with the name change.

**Comment by mrbermell** [comment]
Great. I'll see what I can do. I might also give the merge conflicts a stab.

**Comment by mrbermell** [comment]
I've solved all the merge conflict in #186 . I think this PR should be closed and we merge the new one. I didn't want to make such big commits in your branch.

**Pull request merged**
