### PR TITLE
correct some  rules issues (Tackle and Dodge, Apothecary with KO)

### PR DESCRIPTION
**Pull request by rreche**
I found several minor errors which are corrected in this branch:

- a wrong condition to test is a play can catch or not
- a list of wrong conditions to test if an adjacent player with some skill exists or not
- when someone use an Apothecary on a KO, the player is still on the pitch but stunned (instead of being put on reserve)
- Tackle was not considered for dodge and block results

I have also done two minor changes and I hope it doesn't break anything:
- I change the order between WeatherTable and Fans procedure
- During Setup, I modify the setup reorganization

### CODE REVIEW

**Comment by njustesen** [comment]
Very nice. I will test it soon. Btw. rreche, please get in touch on discord.

**Comment by rreche** [comment]
I change my name on Discord from rr3my to rreche to be sure that people know that it is the same person.

Envoyé de mon iPhone

**Comment by njustesen** [comment]
Can I try your replay module?

**Comment by rreche** [comment]
I am on vacation until Sunday. I will sens it after that.

Envoyé de mon iPhone

**Comment by njustesen** [comment]
Thanks.

**Comment by njustesen** [comment]
Hi Rémy,
Sorry for being impatient, but will you be able to share the replay module sometime this week?
Thanks!

**Pull request merged**
