### PR TITLE
Pathfinding fix to limit only one foul and handoff per path

### PR DESCRIPTION
**Pull request by njustesen**
The pathfinder checked self.can_foul and self.can_handoff to see whether it could do a foul or handoff. This obviously needs to be tied the the state of the node so it's only allowed once. That's implemented in this PR.

Without this check, the pathfinder can actually end in a never-ending-loop.

### CODE REVIEW

**Comment by mrbermell** [comment]
I'll review this weekend. Is the new foul test the one that will go one forever without this fix?

**Comment by njustesen** [comment]
> Is the new foul test the one that will go one forever without this fix?

Yes. It was so hard to reproduce!

**Review by mrbermell — APPROVED** [review]
Looks good :) 
I suggest adding the same test for the handoff

**Comment by njustesen** [comment]
Same test added for handoff. It's passing both with and without the fix - not sure why but that's my least concern :)

**Pull request merged**
