### PR TITLE
Stab fixes and tests

### LINKED ISSUE #159: Exception in method get_block_actions of class game when player has skill STAB
Stack trace:

 game.init()
  File "[...]\ffai\core\game.py", line 108, in init
    self.step(start_action)
  File "[...]\ffai\core\game.py", line 129, in step
    done = self._one_step(self.action)
  File "[...]\ffai\core\game.py", line 421, in _one_step
    self.set_available_actions()
  File "[...]\ffai\core\game.py", line 561, in set_available_actions
    self.state.available_actions = self.state.stack.peek().available_actions()
  File "[...]\ffai\core\procedure.py", line 2949, in available_actions
    actions = self.game.get_block_actions(self.player, blitz=False)
  File "[...]\ffai\core\game.py", line 2450, in get_block_actions
    rolls = [roll + stab_rolls[i] for i, roll in enumerate(rolls)]
  File "[...]\ffai\core\game.py", line 2450, in <listcomp>
    rolls = [roll + stab_rolls[i] for i, roll in enumerate(rolls)]
TypeError: can only concatenate list (not "int") to list

### PR DESCRIPTION
**Pull request by njustesen**
fixes #159 
- #159

### CODE REVIEW

**Comment by mrbermell** [comment]
Brilliant! 
I tried it in the web UI. It works as expected when using blocking but not for Blitzing, the stab option isn't there.

**Comment by njustesen** [comment]
Okay. Thanks. I'll give it another stab 😉

**Comment by mrbermell** [comment]
I see! Then let's fix pathfinding actions!

**Comment by njustesen** [comment]
@mrbermell please add your final review so we can merge this. Thanks

**Review by mrbermell — APPROVED** [review]

**Comment by mrbermell** [comment]
looks great!

**Pull request merged**
